name: riverpod_redux
description: Redux with Riverpod
version: 0.0.1
homepage: https://github.com/kiyosuke/riverpod_redux

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  riverpod: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.0